# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_comboboxForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_cities = QtWidgets.QComboBox(self.centralwidget)
        self.cb_cities.setGeometry(QtCore.QRect(120, 130, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cb_cities.setFont(font)
        self.cb_cities.setObjectName("cb_cities")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(430, 260, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_result.setFont(font)
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.btn_getItem = QtWidgets.QPushButton(self.centralwidget)
        self.btn_getItem.setGeometry(QtCore.QRect(160, 230, 181, 61))
        self.btn_getItem.setObjectName("btn_getItem")
        self.btn_loadItems = QtWidgets.QPushButton(self.centralwidget)
        self.btn_loadItems.setGeometry(QtCore.QRect(160, 310, 181, 61))
        self.btn_loadItems.setObjectName("btn_loadItems")
        self.btn_clearItems = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clearItems.setGeometry(QtCore.QRect(160, 390, 181, 61))
        self.btn_clearItems.setObjectName("btn_clearItems")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_getItem.setText(_translate("MainWindow", "Get Item"))
        self.btn_loadItems.setText(_translate("MainWindow", "Load Items"))
        self.btn_clearItems.setText(_translate("MainWindow", "Clear Items"))
