# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 424)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_number1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_number1.setGeometry(QtCore.QRect(40, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_number1.setFont(font)
        self.lbl_number1.setObjectName("lbl_number1")
        self.lbl_number2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_number2.setGeometry(QtCore.QRect(40, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_number2.setFont(font)
        self.lbl_number2.setObjectName("lbl_number2")
        self.txt_number1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_number1.setGeometry(QtCore.QRect(150, 90, 200, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_number1.setFont(font)
        self.txt_number1.setText("")
        self.txt_number1.setObjectName("txt_number1")
        self.txt_number2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_number2.setGeometry(QtCore.QRect(150, 151, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_number2.setFont(font)
        self.txt_number2.setText("")
        self.txt_number2.setObjectName("txt_number2")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(40, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.btn_subs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_subs.setGeometry(QtCore.QRect(190, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_subs.setFont(font)
        self.btn_subs.setObjectName("btn_subs")
        self.btn_multi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multi.setGeometry(QtCore.QRect(340, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_multi.setFont(font)
        self.btn_multi.setObjectName("btn_multi")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(490, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(40, 290, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(24)
        self.lbl_result.setFont(font)
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_number1.setText(_translate("MainWindow", "Number 1"))
        self.lbl_number2.setText(_translate("MainWindow", "Number 2"))
        self.btn_add.setText(_translate("MainWindow", "Addition"))
        self.btn_subs.setText(_translate("MainWindow", "Substraction"))
        self.btn_multi.setText(_translate("MainWindow", "Multiplication"))
        self.btn_div.setText(_translate("MainWindow", "Division"))
